import { SideNavItemGroup } from './types/sidebarTypes';
import { DashboardIcon } from '@radix-ui/react-icons';
import {
  TicketIcon,
  UserIcon,
  CreditCardIcon,
  CalendarIcon,
  ShareIcon,
  GiftIcon,
  StarIcon,
  MailIcon,
  BadgeDollarSignIcon,
  Shield,
  ArrowLeftRight,
  Settings,
  MessageCircle,
  BellIcon,
  CreditCard,
  Mails,
  ListChecks,
  TrendingUp,
  FileText,
  PanelsTopLeft,
  BarChart3,
  Receipt,
  Package,
  Truck,
  HelpCircle,
  FileText as FileTextIcon,
  Phone,
  MessageSquare,
  Clock,
  Wallet,
  Award,
  ShieldCheck,
  RefreshCw,
  Archive,
  Building,
  MapPin,
  Users,
  Briefcase,
  Target,
  Calculator,
  BookOpen,
  Headphones,
  Palette,
  Key,
  Recycle,
  PhoneOutgoing,
} from 'lucide-react';

export const CUSTOMER_SIDENAV_ITEMS: SideNavItemGroup[] = [
  {
    title: 'Overview',
    menuList: [
      {
        title: 'Dashboard',
        path: '/dashboard',
        role: ['customer'],
        icon: <DashboardIcon />,
      },
      {
        title: 'Profile',
        path: '/dashboard/customers/profile',
        role: ['customer'],
        icon: <UserIcon size={16} />,
      },
      {
        title: 'Notifications',
        path: '/dashboard/notification',
        role: ['customer'],
        icon: <BellIcon size={16} />,
      },
    ],
  },
  {
    title: 'Services',
    menuList: [
      {
        title: 'Tickets',
        path: '/dashboard/customers/tickets',
        role: ['customer'],
        icon: <TicketIcon size={16} />,
      },
      {
        title: 'Bookings',
        path: '/dashboard/customers/bookings',
        role: ['customer'],
        icon: <CalendarIcon size={16} />,
      },
      {
        title: 'Orders',
        path: '/dashboard/customers/orders',
        role: ['customer'],
        icon: <Receipt size={16} />,
      },
      {
        title: 'Buy Sell Trade',
        path: '/dashboard/customers/buy-sell-trade',
        role: ['customer'],
        icon: <ArrowLeftRight size={16} />,
      },
      {
        title: 'Mail-Ins',
        path: '/dashboard/customers/mail-ins',
        role: ['customer'],
        icon: <MailIcon size={16} />,
      },
      {
        title: 'Insurance',
        path: '/dashboard/customers/insurance',
        role: ['customer'],
        icon: <Shield size={16} />,
      },
    ],
  },
  {
    title: 'Financial',
    menuList: [
      {
        title: 'Store Credit',
        path: '/dashboard/customers/store-credit',
        role: ['customer'],
        icon: <BadgeDollarSignIcon size={16} />,
      },
      {
        title: 'Payments',
        path: '/dashboard/customers/payments',
        role: ['customer'],
        icon: <CreditCardIcon size={16} />,
      },
      {
        title: 'Warranty',
        path: '/dashboard/customers/warranty',
        role: ['customer'],
        icon: <ShieldCheck size={16} />,
      },
      {
        title: 'Refunds',
        path: '/dashboard/customers/refunds',
        role: ['customer'],
        icon: <RefreshCw size={16} />,
      },
    ],
  },
  {
    title: 'Rewards & Reviews',
    menuList: [
      {
        title: 'Loyalty Program',
        path: '/dashboard/customers/loyalty',
        role: ['customer'],
        icon: <GiftIcon size={16} />,
      },
      {
        title: 'Referrals',
        path: '/dashboard/customers/referral',
        role: ['customer'],
        icon: <ShareIcon size={16} />,
      },
      {
        title: 'Reviews',
        path: '/dashboard/customers/reviews',
        role: ['customer'],
        icon: <StarIcon size={16} />,
      },
    ],
  },
  {
    title: 'Communications',
    menuList: [
      {
        title: 'Live Chat',
        path: '/dashboard/customers/chat',
        role: ['customer'],
        icon: <MessageSquare size={16} />,
      },
    ],
  },
  {
    title: 'Settings',
    menuList: [
      {
        title: 'Account Settings',
        path: '/dashboard/customers/settings',
        role: ['customer'],
        icon: <Settings size={16} />,
      },
    ],
  },
];
