import { SideNavItemGroup } from './types/sidebarTypes';
import { DashboardIcon } from '@radix-ui/react-icons';
import {
  ArrowLeftRight,
  Boxes,
  DollarSign,
  Goal,
  LucideReceiptPoundSterling,
  Mails,
  NotebookPen,
  PartyPopper,
  ShoppingCart,
  TrendingUp,
  Wrench,
  Calculator,
  Package,
  Calendar,
  MessageCircle,
  ShieldQuestion,
  CreditCard,
  PackageOpen,
  PersonStanding,
  PhoneCall,
  Users,
  Building2,
  BadgeDollarSignIcon,
  PhoneOutgoing,
  MapPin,
  FileText,
  Gift,
  UserIcon,
  Waves,
  ListChecks,
  Bot,
  BadgeCheck,
  Paintbrush,
  KeyRound,
  Recycle,
  SmartphoneCharging,
  Bell,
  CalendarDaysIcon,
  Percent,
  School,
  Radio,
  Ticket,
  Truck,
  PanelsTopLeft,
  Scale,
  CarTaxiFront,
  Activity,
  ShieldCheck,
  Shield,
  AlertCircle,
  Book,
  ImageIcon,
  List,
  Tag,
  Clock,
  Timer,
  UserX,
  Settings,
  Phone,
  Megaphone,
  BarChart3,
  Layers,
  Zap,
  Target,
  Headphones,
  Palette,
  Database,
  Store,
  Receipt,
  Wallet,
  Award,
  Star,
  HelpCircle,
  FileCheck,
  ClipboardList,
  Archive,
  RefreshCw,
  Globe,
  Mail,
  MessageSquare,
  PhoneIncoming,
  Video,
  FileSpreadsheet,
  PieChart,
  TrendingDown,
  DollarSign as DollarSignIcon,
  CreditCard as CreditCardIcon,
  Banknote,
  Calculator as CalculatorIcon,
  Calendar as CalendarIcon,
  Clock as ClockIcon,
  UserCheck,
  UserPlus,
  MapPin as MapPinIcon,
  Building,
  Users as UsersIcon,
  Briefcase,
  GraduationCap,
  FileText as FileTextIcon,
  Shield as ShieldIcon,
  Cog,
  Truck as TruckIcon,
  Bug,
} from 'lucide-react';

export const SIDENAV_ITEMS: SideNavItemGroup[] = [
  {
    title: 'Overview',
    menuList: [
      {
        title: 'Dashboard',
        path: '/dashboard',
        role: ['all'],
        icon: <DashboardIcon />,
      },
      {
        title: 'Analytics',
        path: '/dashboard/analytics',
        role: ['all'],
        icon: <BarChart3 size={16} />,
      },
      // {
      //   title: "Tasks",
      //   path: "/dashboard/task",
      //   role: ["all"],
      //   icon: <ListChecks size={16} />,
      // },
      // {
      //   title: "Notifications",
      //   path: "/dashboard/notification",
      //   role: ["all"],
      //   icon: <Bell size={16} />,
      // },
    ],
  },
  {
    title: 'Operations',
    menuList: [
      // {
      //   title: "Repairs",
      //   path: "/dashboard/repairs",
      //   role: ["admin", "technician", "developer"],
      //   icon: <Wrench size={16} />,
      // },
      // {
      //   title: "Repair Issues",
      //   path: "/dashboard/repairs/issues",
      //   role: ["admin", "technician", "developer"],
      //   icon: <AlertCircle size={16} />,
      // },
      // {
      //   title: "Tickets",
      //   path: "/dashboard/tickets",
      //   role: ["all"],
      //   icon: <Ticket size={16} />,
      // },
      // {
      //   title: "Bookings",
      //   path: "/dashboard/bookings",
      //   role: ["all"],
      //   icon: <Calendar size={16} />,
      // },
      // {
      //   title: "Quotes",
      //   path: "/dashboard/quotes",
      //   role: ["admin", "technician", "developer"],
      //   icon: <FileText size={16} />,
      // },
      // {
      //   title: "Diagnostics",
      //   path: "/dashboard/diagnostics",
      //   role: ["admin", "technician", "developer"],
      //   icon: <Bot size={16} />,
      // },
      // {
      //   title: "IMEI Checker",
      //   path: "/dashboard/repairs/imei-checker",
      //   role: ["admin", "technician", "developer"],
      //   icon: <BadgeCheck size={16} />,
      // },
      {
        title: 'Price Checker',
        path: '/dashboard/price-checker',
        role: ['admin', 'technician', 'developer'],
        icon: <Target size={16} />,
      },
      {
        title: 'Orders',
        path: '/dashboard/pos/orders',
        role: ['all'],
        icon: <Receipt size={16} />,
      },
    ],
  },
  // {
  //   title: "Services",
  //   menuList: [
  //     {
  //       title: "Buy Sell Trade",
  //       path: "/dashboard/buy-sell-trade",
  //       role: ["admin", "developer"],
  //       icon: <ArrowLeftRight size={16} />,
  //     },
  //     {
  //       title: "Customizations",
  //       path: "/dashboard/customizations",
  //       role: ["admin", "developer"],
  //       icon: <Paintbrush size={16} />,
  //     },
  //     {
  //       title: "Unlocks",
  //       path: "/dashboard/unlocks",
  //       role: ["admin", "developer"],
  //       icon: <KeyRound size={16} />,
  //     },
  //     {
  //       title: "Recycling",
  //       path: "/dashboard/recycling",
  //       role: ["admin", "developer"],
  //       icon: <Recycle size={16} />,
  //     },
  //     {
  //       title: "Rental Devices",
  //       path: "/dashboard/rental-devices",
  //       role: ["admin", "developer"],
  //       icon: <PhoneOutgoing size={16} />,
  //     },
  //     {
  //       title: "Franchise",
  //       path: "/dashboard/franchise",
  //       role: ["all"],
  //       icon: <Building2 size={16} />,
  //     },
  //   ],
  // },
  // {
  //   title: "Point of Sale",
  //   menuList: [
  //     {
  //       title: "Register",
  //       path: "/dashboard/pos/register",
  //       role: ["all"],
  //       icon: <ShoppingCart size={16} />,
  //     },
  //     {
  //       title: "Orders",
  //       path: "/dashboard/pos/orders",
  //       role: ["all"],
  //       icon: <Receipt size={16} />,
  //     },
  //     {
  //       title: "Discounts",
  //       path: "/dashboard/pos/discounts",
  //       role: ["all"],
  //       icon: <Percent size={16} />,
  //     },
  //   ],
  // },
  {
    title: 'Inventory & Products',
    menuList: [
      {
        title: 'Inventory Items',
        path: '/dashboard/inventory/items',
        role: ['admin', 'developer'],
        icon: <Boxes size={16} />,
      },
      {
        title: 'Bundles',
        path: '/dashboard/inventory/bundles',
        role: ['admin', 'developer'],
        icon: <Package size={16} />,
      },
      // {
      //   title: "Purchase Orders",
      //   path: "/dashboard/inventory/purchase-orders",
      //   role: ["admin", "developer"],
      //   icon: <ClipboardList size={16} />,
      // },
      {
        title: 'Suppliers',
        path: '/dashboard/inventory/suppliers',
        role: ['admin', 'developer'],
        icon: <Building size={16} />,
      },
      // {
      //   title: "Carriers",
      //   path: "/dashboard/inventory/carriers",
      //   role: ["admin", "developer"],
      //   icon: <Truck size={16} />,
      // },
      // {
      //   title: "Special Parts",
      //   path: "/dashboard/special-parts",
      //   role: ["admin", "developer"],
      //   icon: <PackageOpen size={16} />,
      // },
      {
        title: 'Warranty',
        path: '/dashboard/warranty',
        role: ['admin', 'developer'],
        icon: <ShieldCheck size={16} />,
      },
      {
        title: 'Adjustments',
        path: '/dashboard/inventory/adjustments',
        role: ['admin', 'developer'],
        icon: <RefreshCw size={16} />,
      },
      {
        title: 'Audits',
        path: '/dashboard/inventory/audits',
        role: ['admin', 'developer'],
        icon: <FileCheck size={16} />,
      },
      {
        title: 'Returns',
        path: '/dashboard/inventory/returns',
        role: ['admin', 'developer'],
        icon: <Archive size={16} />,
      },
      {
        title: 'Transfers',
        path: '/dashboard/inventory/transfers',
        role: ['admin', 'developer'],
        icon: <ArrowLeftRight size={16} />,
      },
      {
        title: 'Exchanges',
        path: '/dashboard/inventory/exchanges',
        role: ['admin', 'developer'],
        icon: <RefreshCw size={16} />,
      },
    ],
  },
  {
    title: 'Customers & Staff',
    menuList: [
      {
        title: 'Customer Directory',
        path: '/dashboard/customers',
        role: ['all'],
        icon: <Users size={16} />,
      },
      {
        title: 'Staff Directory',
        path: '/dashboard/staff/directory',
        role: ['all'],
        icon: <UsersIcon size={16} />,
      },
      {
        title: 'Locations',
        path: '/dashboard/locations',
        role: ['all'],
        icon: <MapPin size={16} />,
      },
      // {
      //   title: "Mail Ins",
      //   path: "/dashboard/mail-ins",
      //   role: ["all"],
      //   icon: <Mail size={16} />,
      // },
      // {
      //   title: "Referrals",
      //   path: "/dashboard/referrals",
      //   role: ["all"],
      //   icon: <PersonStanding size={16} />,
      // },
      // {
      //   title: "Loyalty Program",
      //   path: "/dashboard/loyalty",
      //   role: ["all"],
      //   icon: <Gift size={16} />,
      // },
      // {
      //   title: "Store Credit",
      //   path: "/dashboard/store-credit",
      //   role: ["all"],
      //   icon: <BadgeDollarSignIcon size={16} />,
      // },
      // {
      //   title: "Reviews",
      //   path: "/dashboard/reviews",
      //   role: ["all"],
      //   icon: <Star size={16} />,
      // },
      // {
      //   title: "Customer Feedback",
      //   path: "/dashboard/feedback",
      //   role: ["all"],
      //   icon: <MessageSquare size={16} />,
      // },
    ],
  },
  // {
  //   title: "Communications",
  //   menuList: [
  //     {
  //       title: "Phone System",
  //       path: "/dashboard/phone",
  //       role: ["all"],
  //       icon: <Phone size={16} />,
  //     },
  //     {
  //       title: "Email Management",
  //       path: "/dashboard/emails",
  //       role: ["all"],
  //       icon: <Mails size={16} />,
  //     },
  //     {
  //       title: "Campaigns",
  //       path: "/dashboard/campaigns",
  //       role: ["all"],
  //       icon: <Megaphone size={16} />,
  //     },
  //     {
  //       title: "Live Chat",
  //       path: "/dashboard/live-chat",
  //       role: ["all"],
  //       icon: <MessageSquare size={16} />,
  //     },
  //     {
  //       title: "Contacts",
  //       path: "/dashboard/contacts",
  //       role: ["all"],
  //       icon: <MessageCircle size={16} />,
  //     },
  //   ],
  // },
  // {
  //   title: "Accounting",
  //   menuList: [
  //     {
  //       title: "Bills",
  //       path: "/dashboard/accounting/bills",
  //       role: ["admin"],
  //       icon: <DollarSign size={16} />,
  //     },
  //     {
  //       title: "Goals",
  //       path: "/dashboard/accounting/goals",
  //       role: ["admin"],
  //       icon: <Goal size={16} />,
  //     },
  //     {
  //       title: "Transactions",
  //       path: "/dashboard/accounting/transactions",
  //       role: ["admin"],
  //       icon: <ArrowLeftRight size={16} />,
  //     },
  //     {
  //       title: "Balance",
  //       path: "/dashboard/accounting/balance",
  //       role: ["admin"],
  //       icon: <Banknote size={16} />,
  //     },
  //     {
  //       title: "Loans",
  //       path: "/dashboard/accounting/loans",
  //       role: ["admin"],
  //       icon: <LucideReceiptPoundSterling size={16} />,
  //     },
  //     {
  //       title: "Payroll",
  //       path: "/dashboard/accounting/payroll",
  //       role: ["admin"],
  //       icon: <CreditCard size={16} />,
  //     },
  //     {
  //       title: "Tax",
  //       path: "/dashboard/accounting/tax",
  //       role: ["admin"],
  //       icon: <CarTaxiFront size={16} />,
  //     },
  //   ],
  // },
  // {
  //   title: "Workforce",
  //   menuList: [
  //     {
  //       title: "Overview",
  //       path: "/dashboard/workforce",
  //       role: ["admin"],
  //       icon: <Clock size={16} />,
  //     },
  //     {
  //       title: "Scheduling",
  //       path: "/dashboard/workforce/scheduling",
  //       role: ["admin"],
  //       icon: <Calendar size={16} />,
  //     },
  //     {
  //       title: "Time Tracking",
  //       path: "/dashboard/workforce/time-tracking",
  //       role: ["admin"],
  //       icon: <Timer size={16} />,
  //     },
  //     {
  //       title: "My Workforce",
  //       path: "/dashboard/workforce/my-workforce",
  //       role: ["all"],
  //       icon: <Clock size={16} />,
  //     },
  //     {
  //       title: "Absence Management",
  //       path: "/dashboard/workforce/absence",
  //       role: ["admin"],
  //       icon: <UserX size={16} />,
  //     },
  //   ],
  // },
  {
    title: 'Education',
    menuList: [
      {
        title: 'Blogs',
        path: '/dashboard/blogs',
        role: ['all'],
        icon: <FileTextIcon size={16} />,
      },
      {
        title: 'Faqs',
        path: '/dashboard/faqs',
        role: ['all'],
        icon: <HelpCircle size={16} />,
      },
      // {
      //   title: "Repair Guides",
      //   path: "/dashboard/repair-guides",
      //   role: ["admin", "technician", "developer"],
      //   icon: <Book size={16} />,
      // },
    ],
  },
  {
    title: 'Tools & Resources',
    menuList: [
      {
        title: 'Calculator',
        path: '/dashboard/calculator',
        role: ['all'],
        icon: <Calculator size={16} />,
      },
      // {
      //   title: "Notes",
      //   path: "/dashboard/notes",
      //   role: ["all"],
      //   icon: <NotebookPen size={16} />,
      // },
      {
        title: 'Announcements',
        path: '/dashboard/announcement',
        role: ['all'],
        icon: <PartyPopper size={16} />,
      },
      {
        title: 'Image Library',
        path: '/dashboard/image-library',
        role: ['admin', 'developer'],
        icon: <ImageIcon size={16} />,
      },
      {
        title: 'Tags Management',
        path: '/dashboard/tags',
        role: ['admin', 'developer'],
        icon: <Tag size={16} />,
      },
      {
        title: 'Terms & Legal',
        path: '/dashboard/terms',
        role: ['all'],
        icon: <Scale size={16} />,
      },
      // {
      //   title: "Error Tracking",
      //   path: "/dashboard/error-tracking",
      //   role: ["admin", "developer"],
      //   icon: <Bug size={16} />,
      // },
    ],
  },
  {
    title: 'Settings',
    menuList: [
      {
        title: 'General Settings',
        path: '/dashboard/settings',
        role: ['all'],
        icon: <Settings size={16} />,
      },
      {
        title: 'Shipping Settings',
        path: '/dashboard/settings/shipping',
        role: ['all'],
        icon: <Truck size={16} />,
      },
      // {
      //   title: "Staff Profile",
      //   path: "/dashboard/staff/profile",
      //   role: ["all"],
      //   icon: <UserIcon size={16} />,
      // },
    ],
  },
];
